In [3]:
import pandas as pd
import google_conf
import json

In [8]:
emlap_catalogue = google_conf.setup(sheet_url="https://docs.google.com/spreadsheets/d/1QfepoyysD1Cu12KcMAMfc6gqGzXzVUekPtXDbxLixr4/edit?usp=sharing", service_account_path="../../../ServiceAccountsKey.json")


# Get the data and transpose
emlap_metadata_raw = google_conf.get_as_dataframe(emlap_catalogue.worksheet("Catalogue"), row=1, include_index=False)
emlap_metadata_raw.head(5)

,basic_info,"Augurello, Chrysopoeia","Pseudo-Lull, Secretis","Pantheus, Ars Transmutatione","Anon, Vera alchemiae","Pantheus, Voarchadumia","Savonarola, De arte conficiendi aquam vitae","Anon, Rosarium philosophorum","Severinus, Epistola","Vegius, Inter inferiora corpora",...,"Ruland, Progymnasmata alchemiae","Drebbel, Tractatus Duo","Sala, Chrysologia","Anon, Musaeum Hermeticum","Fabre, Alchymista christianus","Agricola, Galerazeya","Van Helmont, Opuscula","Burggravius, Biolychnium","Francus, De arte chemica","Van Helmont, Ortus medicinae"
0,filenames,100001_Augurello1515_Chrysopoeia_GB_Noscemus,100002_Pseudo-Lull1518_De secretis_naturae_MDZ...,100003_Pantheus1518_Ars_Transmutationis_Metall...,100004_Anon1561_Verae_Alchemiae_MDZ_MBS,100005_Pantheus1530_Voarchadumia_ONB,100006_Savonarola1532_De_arte_conficiendi_aqua...,100007_Anon1550_Rosarium_philosophorum_ER_ZZ,100008_Severinus1572_Epistola_MBZ_MBS,100009_Vegius1518_Inter_inferiora_corpora_disp...,...,100091_Ruland1607_Progymnasmata_alchemiae_MDZ_MBS,100092_Drebbel1621_Tractatus_duo_VD17_Halle,100093_Sala1622_Chrysologia_MBZ_MBS,100094_Anon1625_Musaeum_hermeticum_VD17_SLUB,100095_Fabre1632_Alchymista_christianus_ONB,100096_Agricola1631_Galerazeya_GB_BL,100097_Van_Helmont1644_Opuscula_medica_MDZ_MBS,100098_Burggravius1630_Biolychnium_VD17_SLUB,100099_Francus1607_De Arte_Chemica_VD17_Halle,100100_Van_Helmont1648_Ortus_medicinae_MDZ_MBS
1,no.,100001,100002,100003,100004,100005,100006,100007,100008,100009,...,100091,100092,100093,100094,100095,100096,100097,100098,100099,100100
2,is_done,True,True,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,True
3,is_noscemus,True,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,True
4,if_noscemus_id,713324,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,688159

In [9]:
emlap_metadata_raw.set_index("basic_info", inplace=True)
emlap_metadata_raw.index.name = None
emlap_metadata= emlap_metadata_raw.T
emlap_metadata.index = emlap_metadata.index.astype(str)
emlap_metadata.rename_axis("working_title", inplace=True)
emlap_metadata.head(5)

,filenames,no.,is_done,is_noscemus,if_noscemus_id,AUTHORSHIP,is_one_author,#if more than 1 author skip section and choose compendium below,is_author_known,author_name,...,publisher_name_alternatives,publisher_comments,CONTENTS,genre,subject,SOURCE OF FILE,link,source_of_file,origin_of_copy,other_notes
working_title,,,,,,,,,,,,,,,,,,,,,
"Augurello, Chrysopoeia",100001_Augurello1515_Chrysopoeia_GB_Noscemus,100001,True,True,713324,NaN,True,NaN,True,"Augurelli, Giovanni Aurelio",...,NaN,NaN,NaN,didactic poem,alchemy,NaN,https://wiki.uibk.ac.at/noscemus/Chrysopoeia,GB,Noscemus,NaN
"Pseudo-Lull, Secretis",100002_Pseudo-Lull1518_De secretis_naturae_MDZ...,100002,True,False,NaN,NaN,True,NaN,True,Pseudo-Lull,...,NaN,NaN,NaN,treatise,"alchemy, medicine",NaN,https://www.digitale-sammlungen.de/en/view/bsb...,MDZ,MBS,NaN
"Pantheus, Ars Transmutatione",100003_Pantheus1518_Ars_Transmutationis_Metall...,100003,True,False,NaN,NaN,True,NaN,True,"Panteo, Giovanni Agostino",...,NaN,NaN,NaN,treatise,alchemy,NaN,https://www.google.co.uk/books/edition/Ars_Tra...,GB,BL,NaN
"Anon, Vera alchemiae",100004_Anon1561_Verae_Alchemiae_MDZ_MBS,100004,True,False,NaN,NaN,True,NaN,True,"Gratarolo, Guilelmo",...,NaN,NaN,NaN,"compendium, florilegium",alchemy,NaN,https://mdz-nbn-resolving.de/details:bsb10141168,MDZ,MBS,NaN
"Pantheus, Voarchadumia",100005_Pantheus1530_Voarchadumia_ONB,100005,True,False,NaN,NaN,True,NaN,True,"Panteo, Giovanni Agostino",...,NaN,NaN,NaN,treatise,alchemy,NaN,https://data.onb.ac.at/rep/10588E49,ONB,ONB,NaN

In [12]:
def load_sentences_data(id):
    dir = "../data/sents_data/"
    filename = str(id) + ".json"
    with open(dir + filename, "r") as f:
        sents_data = json.load(f)
    return sents_data

def count_tokens(id):
    try:
        sents_data = load_sentences_data(id)
        tokens_N = sum([len(sent_data[3]) for sent_data in sents_data])
    except:
        tokens_N = 0
    return tokens_N
emlap_metadata["tokens_N"] = emlap_metadata["no."].apply(count_tokens)

In [13]:
emlap_metadata["tokens_N"].sum()

3495212

In [14]:
emlap_metadata.to_csv("../data/emlap_metadata.csv", sep=";") # , index=True)

In [15]:
emlap_metadata.to_csv("/srv/data/tome/tome-corpus/emlap_metadata.csv", sep=";") # , index=True)