In [43]:
import json
import os
import pandas as pd
import numpy as np

In [2]:
emlap_metadata = pd.read_csv("/srv/data/tome/tome-corpus/emlap_metadata.csv", sep=";")
ids = emlap_metadata["No."]

In [3]:
emlap_metadata.head(10)

,working_title,No.,is_done,is_noscemus,if_noscemus_id,"#if is_noscemus = True, don't transcribe",AUTHORSHIP,is_one_author,#if more than 1 author skip section and choose compendium below,is_author_known,...,source_of_file,origin_of_copy,REFERENCES,catalogue_reference,secondary_references,general_comments,OTHER,filename,Unnamed: 64,tokens_N
0,"Augurello, Chrysopoeia",100001,True,True,713324.0,NaN,NaN,True,NaN,True,...,Noscemus,Unknown,NaN,Noscemus Wiki,Soranzo 2019,The 1518 Basel version is also in Noscemus,NaN,"Augurello,_Giovanni_Aurelio_-_Chrysopoeia__Ven...",NaN,23718
1,"Pseudo-Lull, Secretis",100002,True,False,NaN,NaN,NaN,True,NaN,True,...,MDZ,MBS,NaN,Hirsch 1950,NaN,"There is a prior, 1514 edition of De secretis ...",NaN,Pseudo-Lull1518_De_secretis_naturae_MDZ.pdf,NaN,24673
2,"Pantheus, Ars Transmutatione",100003,True,False,NaN,NaN,NaN,True,NaN,True,...,GB,BL,NaN,NaN,NaN,This book was first published in 1518 with an ...,NaN,Pantheus1518_Ars_Transmutationis_Metallicae_BL...,NaN,8646
3,"Pantheus, Commentarium",100004,True,False,NaN,NaN,NaN,True,NaN,True,...,MDZ,MSB,NaN,NaN,NaN,This 1519 book is catalogued wrongly by many l...,NaN,Pantheus1519_Commentarium_Transmutationis_Meta...,NaN,3521
4,"Pantheus, Voarchadumia",100005,True,False,NaN,NaN,NaN,True,NaN,True,...,ONB,ONB,NaN,NaN,NaN,Dedicated to Leonellus Marquis of Estense,NaN,Pantheus1530_Voarchadumia_ONB.pdf,NaN,20386
5,"Savonarola, De arte conficiendi aquam vitae",100006,True,False,NaN,NaN,NaN,True,NaN,True,...,ONB,ONB,NaN,Hirsch 1950,NaN,NaN,NaN,Savonarola1532_De_arte_conficiendi_aquam_vitae...,NaN,15237
6,"Anon, Rosarium philosophorum",100007,True,False,NaN,NaN,NaN,False,NaN,False,...,ER,ZZ,NaN,NaN,NaN,NaN,NaN,Anon1550_Rosarium_philosophorum_Erara.pdf,NaN,36755
7,"Severinus, Epistola",100008,True,False,NaN,NaN,NaN,True,NaN,True,...,MDZ,MBS,NaN,NaN,NaN,NaN,NaN,Severinus1572_Epistola_MBZ_MBS.pdf,NaN,2265
8,"Vegius, Inter inferiora corpora",100009,True,False,NaN,NaN,NaN,False,NaN,False,...,ONB,ONB,NaN,Hirsch 1950,NaN,"This is the second edition, the first was publ...",NaN,Vegius1518_Inter_inferiora_corpora_disputatio_...,NaN,27934
9,"Bracesco, De alchimia dialogi duo",100010,True,False,NaN,NaN,NaN,True,NaN,True,...,IA,UCM,NaN,Ferguson 1906,NaN,Translation from Italian,NaN,Bracesco1548_De_alchemia_dialogi_II_IA_Madrid.pdf,NaN,42220

In [4]:
emlap_id_filename_dict = dict(zip(emlap_metadata["No."], emlap_metadata["filename"]))
emlap_id_filename_dict

{100001: 'Augurello,_Giovanni_Aurelio_-_Chrysopoeia__Venice_1515_pdf.pdf',
 100002: 'Pseudo-Lull1518_De_secretis_naturae_MDZ.pdf',
 100003: 'Pantheus1518_Ars_Transmutationis_Metallicae_BL_GB.pdf',
 100004: 'Pantheus1519_Commentarium_Transmutationis_Metallicae_MDZ.pdf',
 100005: 'Pantheus1530_Voarchadumia_ONB.pdf',
 100006: 'Savonarola1532_De_arte_conficiendi_aquam_vitae_ONB.pdf',
 100007: 'Anon1550_Rosarium_philosophorum_Erara.pdf',
 100008: 'Severinus1572_Epistola_MBZ_MBS.pdf',
 100009: 'Vegius1518_Inter_inferiora_corpora_disputatio_ONB.pdf',
 100010: 'Bracesco1548_De_alchemia_dialogi_II_IA_Madrid.pdf',
 100011: 'De_alchemia1541_MDZ_MBS.pdf',
 100012: 'Gessner1552_Thesaurus_Euonymi_Philiatri_ER_ZZ.pdf',
 100013: 'Ulstad1525_Coelum_philosophorum_IA_BIUSP_pdf.pdf',
 100014: 'Toxites1567_Spongia_stibii_MDZ_MBS.pdf',
 100015: 'Gessner1569_Thesaurus_Euonymi_Philiatri_Liber_Secundus_MDZ_MBS.pdf',
 100016: 'Bonus1546_Pretiosa_Margarita_Novella_ONB.pdf',
 100017: 'Bodenstein1559_Isagoge_MDZ_MBS.pdf',
 100018: 'Trevisanus1567_De_alchemia_MDZ_MBS.pdf',
 100019: 'Ulstadt1526_De_epidemia_ONB.pdf',
 100020: 'Dorn1569_Artificii_chymistici_MDZ_MBS.pdf',
 100021: 'Dorn1567_Clavis_totius_philosophiae_chymisticae_ONB_pdf.pdf',
 100022: 'Anon1550_De_alchemia_opuscula_MDZ_MBS.pdf',
 100023: 'Paracelsus1553_Labyrinthus_medicorum_errantium_MDZ_MBS_pdf.pdf',
 100024: 'Fanianus1560_De_arte_metallicae_ONB_pdf.pdf',
 100025: 'Pseudo-Lull1563_Codicillus_MDZ_MBS_pdf.pdf',
 100026: 'Garlandius1560_Compendium_Alchemiae_SLUB_pdf.pdf',
 100027: 'Pseudo-Paracelsus1568_Pyrophilia_vexationumque_ONB.pdf',
 100028: 'Pedemontanus1563_De_Secretis_MDZ_MBS.pdf',
 100029: 'Paracelsus1560_Libri_quatuor_de_vita_longa_MDZ_MBS.pdf',
 100030: 'Rupescissa1561_De_Consideratione_Quintae_essentie_rerum_GB.pdf',
 100031: 'Phaedro1562_Aquila_coelestis_MBZ_MBS.pdf',
 100032: 'Ventura1571_De_ratione_conficiendi_lapis_MBZ_MBS.pdf',
 100033: 'Paracelsus1582_Centum_quindecim_curationes_MDZ_MBS.pdf',
 100034: 'Penotus1594_Tractatus_varii_MDZ_MBS.pdf',
 100035: 'Dorn1570_Lapis_metaphysicus_MDZ_MBS_pdf.pdf',
 100036: 'Vadis1595_Dialogus_IA_Wellcome.pdf',
 100037: 'DuChesne1575_Ad_Iacobi_Auberti_MDZ_Augsburg.pdf',
 100038: 'Auriferae_artisI1572_MBZ_Augsburg.pdf',
 100039: 'Pseudo-Democritus1572_Ars_magna.pdf',
 100040: 'Pseudo-Lull1567_Mercuriorum_liber_MDZ_MBS.pdf',
 100041: 'Senior1560_De_chemia_senioris_MDZ_MBS.pdf',
 100042: 'Pseudo-Paracelsus1568_De_summis_naturae_mysteriis_MDZ_MBS.pdf',
 100043: 'DuChesne1575_Sclopetarius_MDZ_Augsburg.pdf',
 100044: 'Dorn1578_Theophrasti_Germani_Principis_MDZ_MBS.pdf',
 100045: 'Dorn1583_De_Naturae_luce_physica_MDZ_MBS.pdf',
 100046: 'Dorn1584_Commentaria_in_Archidoxorum_MDZ_MBS.pdf',
 100047: 'Portaleone1584_De_auro_dialogi_tres_ONB.pdf',
 100048: 'Pseudo-Aquinas1579_Secreta_alchemiae_magnalia_ONB.pdf',
 100049: 'Rossi1585_De_destillatione_MDZ_MBS.pdf',
 100050: 'Barnaud1599_Quadriga_aurifera_IA_Madrid.pdf',
 100051: 'Ruland1564_Medicina_practica_recens_MDZ_MDS.pdf',
 100052: 'Khunrath1599_Confessio_de_chao_chymicorum_MDZ_MBS.pdf',
 100053: 'Mirandola1586_De_auro_libri_tres_MDZ_MBS.pdf',
 100054: 'Moffett_De_iure_et_praestantia_MDZ_MBS.pdf',
 100055: 'Erastus1578_Disputatio_de_auro_potabili_MDZ_MBS.pdf',
 100056: 'Claveus1598_Apologia_crysopoeiae_MDZ_MBS.pdf',
 100057: 'Hagecius1585_De_cervisia_ejusque_conficiendi_ratione.pdf',
 100058: 'Hagecius1596_Actio_medica_ER_UBB.pdf',
 100059: 'Suavius1567_Theophrasti_Paracelsi_Philosophiae_ONB.pdf',
 100060: 'Witestein1583_Disceptatio_philosophica_MDZ_MBS.pdf',
 100061: 'Moffett1588_Nosomantica_Hippocrates_ONB.pdf',
 100062: 'Albertus1569_De_concordantia_Hippocraticorum_et_Paracelsistarum_MDZ_MBS.pdf',
 100063: 'Libavius1595_Rerum_chymicarum_epistolica_liber_primus_MDZ_MBS.pdf',
 100064: 'Trevisanus1583_De_chymico_miraculo_MDZ_MBS.pdf',
 100065: 'Libavius1594_Neoparacelsica_MDZ_MBS.pdf',
 100066: 'Suchten1575_De_secretis_antimonii_ONB.pdf',
 100067: 'Wecker1582_De_secretis_ONB.pdf',
 100068: 'Pseudo-Paracelsus1577_Aurora_Thesaurusque_Philosophorum_ONB.pdf',
 100069: 'Severinus1571_Idea_medicinae_MDZ_MBS.pdf',
 100070: 'Libavius,_Andreas_-_Alchemia_Libavii__Frankfurt_am_Main_1597.pdf',
 100071: 'Pseudo-Lull1566_Testamentum_MDZ_MBS.pdf',
 100072: 'Andernach1571_De_medicina_veteri_et_novi_MDZ_MBS.pdf',
 100073: 'Greverus1599_Secretum_MDZ_MBS.pdf',
 100074: 'Hoghelande1595_De_lapidis_physici_conditionibus_MDZ_MBS.pdf',
 100075: 'Dorn1581_Fasciculus_Paracelsicae_MDZ_MBS.pdf'}

In [5]:
source_path = "/srv/data/tome/tome-corpus/sents_data_id_jsons_v3-0/"

In [6]:
os.listdir(source_path)[:10]

['100044.json',
 '100034.json',
 '100014.json',
 '100060.json',
 '100010.json',
 '100068.json',
 '100043.json',
 '100072.json',
 '100041.json',
 '100012.json']

In [7]:
pdf_dir = "/srv/data/tome/tome-corpus/emlap_raw_2025-03-10/"
os.listdir(pdf_dir)[:10]

['1837264',
 '1837267',
 '1625742',
 '1795813',
 '1776984',
 '3054123',
 '2934943',
 '1731784',
 '1791205',
 '3197805']

In [8]:
filenames = [f for f in os.listdir(source_path) if ".json" in f]
len(filenames)

75

In [9]:
#metadata_table_long = pd.read_json("../data/metadata_table_long.json")

In [10]:
emlaps_sents_data = []
for filename in filenames:
    f_sents_data = json.load(open(source_path + filename, "rb"))
    emlaps_sents_data.extend(f_sents_data)

In [11]:
emlaps_sents_data[:10]

[[100044,
  0,
  'rum omnium, in uniuersum facile Principis.',
  [['rum', 'rus', 'NOUN', [0, 3], [3], [4]],
   ['omnium', 'omnis', 'DET', [4, 10], [3], [4]],
   [',', ',', 'PUNCT', [10, 11], [3], [4]],
   ['in', 'in', 'ADP', [12, 14], [3], [4]],
   ['uniuersum', 'uniuersus', 'DET', [15, 24], [3], [4]],
   ['facile', 'facile', 'ADV', [25, 31], [3], [5]],
   ['Principis', 'principis', 'NOUN', [32, 41], [3], [5]],
   ['.', '.', 'PUNCT', [41, 42], [3], [5]]]],
 [100044,
  1,
  'De restituta utriusque Medicinae uera Praxi.',
  [['De', 'de', 'ADP', [0, 2], [3], [6]],
   ['restituta', 'restituo', 'NOUN', [3, 12], [3], [6]],
   ['utriusque', 'uterque', 'DET', [13, 22], [3], [6]],
   ['Medicinae', 'Medicinus', 'ADJ', [23, 32], [3], [6]],
   ['uera', 'uerus', 'ADJ', [33, 37], [3], [6]],
   ['Praxi', '', 'NOUN', [38, 43], [3], [7]],
   ['.', '.', 'PUNCT', [43, 44], [3], [7]]]],
 [100044,
  2,
  'Gerardo Dorn Doctore Physico, ac interprete Germanico, in hunc ordinem recolligente.',
  [['Gerardo', 'Gherardus', 'PROPN', [0, 7], [3], [9]],
   ['Dorn', '', 'PROPN', [8, 12], [3], [9]],
   ['Doctore', 'doctor', 'PROPN', [13, 20], [3], [9]],
   ['Physico', 'physicus', 'PROPN', [21, 28], [3], [9]],
   [',', ',', 'PUNCT', [28, 29], [3], [9]],
   ['ac', 'atque', 'CCONJ', [30, 32], [3], [9]],
   ['interprete', 'interpres', 'VERB', [33, 43], [3], [9]],
   ['Germanico', 'Germanicus', 'PROPN', [44, 53], [3], [9, 10]],
   [',', ',', 'PUNCT', [53, 54], [3], [10]],
   ['in', 'in', 'ADP', [55, 57], [3], [10]],
   ['hunc', 'hic', 'DET', [58, 62], [3], [10]],
   ['ordinem', 'ordo', 'NOUN', [63, 70], [3], [10]],
   ['recolligente', 'recolligo', 'VERB', [71, 83], [3], [10]],
   ['.', '.', 'PUNCT', [83, 84], [3], [10]]]],
 [100044,
  3,
  'Ad Illustriss.',
  [['Ad', 'ad', 'ADP', [0, 2], [3], [11]],
   ['Illustriss', 'illustriss', 'PROPN', [3, 13], [3], [11]],
   ['.', '.', 'PUNCT', [13, 14], [3], [11]]]],
 [100044,
  4,
  'ac Potentiss.',
  [['ac', 'atque', 'CCONJ', [0, 2], [3], [11]],
   ['Potentiss', 'potentiss', 'PROPN', [3, 12], [3], [11]],
   ['.', '.', 'PUNCT', [12, 13], [3], [11]]]],
 [100044,
  5,
  'Prin cip.',
  [['Prin', 'prin', 'NOUN', [0, 4], [3], [11]],
   ['cip', 'cipc', 'VERB', [5, 8], [3], [11]],
   ['.', '.', 'PUNCT', [8, 9], [3], [11]]]],
 [100044,
  6,
  'D. Francisc.',
  [['D.', 'D.', 'PUNCT', [0, 2], [3], [11]],
   ['Francisc', 'Franciscus', 'PROPN', [3, 11], [3], [11]],
   ['.', '.', 'PUNCT', [11, 12], [3], [11]]]],
 [100044,
  7,
  'Ualesium, Andegauorum, Biturigum, Alenconium, Turonensium, &c. Ducem.',
  [['Ualesium', 'Ualesius', 'PROPN', [0, 8], [3], [12]],
   [',', ',', 'PUNCT', [8, 9], [3], [12]],
   ['Andegauorum', 'Andegauus', 'PROPN', [10, 21], [3], [12]],
   [',', ',', 'PUNCT', [21, 22], [3], [12]],
   ['Biturigum', 'Biturigus', 'PROPN', [23, 32], [3], [12]],
   [',', ',', 'PUNCT', [32, 33], [3], [12]],
   ['Alenconium', 'Alenconius', 'PROPN', [34, 44], [3], [13]],
   [',', ',', 'PUNCT', [44, 45], [3], [13]],
   ['Turonensium', 'Turonensius', 'PROPN', [46, 57], [3], [13]],
   [',', ',', 'PUNCT', [57, 58], [3], [13]],
   ['&', '&', 'PUNCT', [59, 60], [3], [13]],
   ['c.', 'c.', 'ADJ', [60, 62], [3], [13]],
   ['Ducem', 'dux', 'NOUN', [63, 68], [3], [13]],
   ['.', '.', 'PUNCT', [68, 69], [3], [13]]]],
 [100044,
  8,
  'Alterius Non Sit Qui Suus Esse Potest Cum priuileg.',
  [['Alterius', 'alterius', 'ADV', [0, 8], [3], [14]],
   ['Non', 'non', 'PART', [9, 12], [3], [14]],
   ['Sit', 'sum', 'AUX', [13, 16], [3], [14]],
   ['Qui', 'qui', 'PRON', [17, 20], [3], [15]],
   ['Suus', 'suus', 'ADJ', [21, 25], [3], [15]],
   ['Esse', 'sum', 'AUX', [26, 30], [3], [15]],
   ['Potest', 'possum', 'VERB', [31, 37], [3], [15]],
   ['Cum', 'cum', 'SCONJ', [38, 41], [3], [19]],
   ['priuileg', 'priuileg', 'ADJ', [42, 50], [3], [19]],
   ['.', '.', 'PUNCT', [50, 51], [3], [19]]]],
 [100044,
  9,
  'Caesareae ac Regiae maiest.',
  [['Caesareae', 'Caesarea', 'PROPN', [0, 9], [3], [19]],
   ['ac', 'atque', 'CCONJ', [10, 12], [3], [19]],
   ['Regiae', 'Regius', 'ADJ', [13, 19], [3], [19]],
   ['maiest', 'maisum', 'VERB', [20, 26], [3], [19]],
   ['.', '.', 'PUNCT', [26, 27], [3], [19]]]]]

In [12]:
[sent_data for sent_data in emlaps_sents_data if "Alchy" in sent_data[2]]

[[100044,
  7643,
  'Alchymille, M. ii.',
  [['Alchymille', 'Alchymille', 'PROPN', [0, 10], [299], [9]],
   [',', ',', 'PUNCT', [10, 11], [299], [9]],
   ['M.', 'M.', 'PUNCT', [12, 14], [299], [9]],
   ['ii', 'is', 'NUM', [15, 17], [299], [9]],
   ['.', '.', 'PUNCT', [17, 18], [299], [9]]]],
 [100034,
  809,
  'Hoc regulo plura ac diuersa tam in medicina quam in Alchymia fiunt:',
  [['Hoc', 'hic', 'DET', [0, 3], [77], [21]],
   ['regulo', 'regulus', 'VERB', [4, 10], [77], [21]],
   ['plura', 'plus', 'DET', [11, 16], [77], [21]],
   ['ac', 'atque', 'CCONJ', [17, 19], [77], [21]],
   ['diuersa', 'diuersus', 'ADJ', [20, 27], [77], [21]],
   ['tam', 'tam', 'ADV', [28, 31], [77], [21]],
   ['in', 'in', 'ADP', [32, 34], [77], [21]],
   ['medicina', 'medicina', 'NOUN', [35, 43], [77], [22]],
   ['quam', 'quam', 'SCONJ', [44, 48], [77], [22]],
   ['in', 'in', 'ADP', [49, 51], [77], [22]],
   ['Alchymia', 'alchymia', 'PROPN', [52, 60], [77], [22]],
   ['fiunt', 'facio', 'VERB', [61, 66], [77], [22]],
   [':', ':', 'PUNCT', [66, 67], [77], [22]]]],
 [100060,
  431,
  'Si quis asserat hoc agens coelum esse, hoc uerum erit tanquam causa uniuersalis, sed cum haec sine causa secunda nihil operatur, alio agente particulari mixta egent ut gignantur, nec erit uirtus mineralis, nam sic accidens esset, & illud inconueniens subsequeretur, quod substantia gigneretur ab accidenti, hec substantia non erit materia, quoniam proprium materiae est pari, & non agere, ergo si forma erit, nec abiuncta & separata, ex quo alicuius corporis forma, quia corpus hoc uniuersa mineralia per suam formam gigneret, quod falsum est, dicamus igitur calidu & frigidum tanquam instrumenta, cum uaria ac diuersa mineralia efficiunt, non nisi in gignentium uirture, que eiusdem speciei sunt, cum genitis producunt, quare aurum nisi ab auro, & caetera mineralia a consimilibus specie producuntur, quod Alchymiste comprobant, cu aurum efficere student, illud multis rebus permiscent, quod quidem recta cum ratione factum est, nam ea miscentur, ut materiam praeparent, atque afficiant, que cum disposita est, tunc aurum aurum producere poterit, ex his pater, cum aliquid producere uolumus, ut consimilia eligamus, ut ab eis perfectius aliquod oriri possit, postquam declarauimus unde ortum habeant hec omnia.',
  [['Si', 'si', 'SCONJ', [0, 2], [46], [25]],
   ['quis', 'quis', 'ADJ', [3, 7], [46], [25]],
   ['asserat', 'assero', 'VERB', [8, 15], [46], [25]],
   ['hoc', 'hic', 'DET', [16, 19], [46], [25]],
   ['agens', 'ago', 'NOUN', [20, 25], [46], [25]],
   ['coelum', 'coelum', 'NOUN', [26, 32], [46], [25, 26]],
   ['esse', 'sum', 'AUX', [33, 37], [46], [26]],
   [',', ',', 'PUNCT', [37, 38], [46], [26]],
   ['hoc', 'hic', 'DET', [39, 42], [46], [26]],
   ['uerum', 'uerus', 'ADJ', [43, 48], [46], [26]],
   ['erit', 'sum', 'AUX', [49, 53], [46], [26]],
   ['tanquam', 'tamquam', 'ADV', [54, 61], [46], [26]],
   ['causa', 'causa', 'NOUN', [62, 67], [46], [26]],
   ['uniuersalis', 'uniuersalis', 'ADJ', [68, 79], [46], [26, 27]],
   [',', ',', 'PUNCT', [79, 80], [46], [27]],
   ['sed', 'sed', 'CCONJ', [81, 84], [46], [27]],
   ['cum', 'cum', 'SCONJ', [85, 88], [46], [27]],
   ['haec', 'hic', 'DET', [89, 93], [46], [27]],
   ['sine', 'sine', 'ADP', [94, 98], [46], [27]],
   ['causa', 'causa', 'NOUN', [99, 104], [46], [27]],
   ['secunda', 'secundus', 'ADJ', [105, 112], [46], [27]],
   ['nihil', 'nihil', 'PRON', [113, 118], [46], [28]],
   ['operatur', 'operor', 'VERB', [119, 127], [46], [28]],
   [',', ',', 'PUNCT', [127, 128], [46], [28]],
   ['alio', 'alius', 'DET', [129, 133], [46], [28]],
   ['agente', 'ago', 'NOUN', [134, 140], [46], [28]],
   ['particulari', 'particularis', 'ADJ', [141, 152], [46], [28]],
   ['mixta', 'mixtus', 'VERB', [153, 158], [46], [28]],
   ['egent', 'egeo', 'VERB', [159, 164], [47], [1]],
   ['ut', 'ut', 'SCONJ', [165, 167], [47], [1]],
   ['gignantur', 'gigno', 'VERB', [168, 177], [47], [1]],
   [',', ',', 'PUNCT', [177, 178], [47], [1]],
   ['nec', 'neque', 'CCONJ', [179, 182], [47], [1]],
   ['erit', 'sum', 'AUX', [183, 187], [47], [1]],
   ['uirtus', 'uirtus', 'NOUN', [188, 194], [47], [1]],
   ['mineralis', 'mineralis', 'ADJ', [195, 204], [47], [1, 2]],
   [',', ',', 'PUNCT', [204, 205], [47], [2]],
   ['nam', 'nam', 'PART', [206, 209], [47], [2]],
   ['sic', 'sic', 'ADV', [210, 213], [47], [2]],
   ['accidens', 'accido', 'NOUN', [214, 222], [47], [2]],
   ['esset', 'sum', 'AUX', [223, 228], [47], [2]],
   [',', ',', 'PUNCT', [228, 229], [47], [2]],
   ['&', '&', 'PUNCT', [230, 231], [47], [2]],
   ['illud', 'ille', 'DET', [232, 237], [47], [2]],
   ['inconueniens', 'inconueniens', 'ADJ', [238, 250], [47], [2, 3]],
   ['subsequeretur', 'subsequor', 'VERB', [251, 264], [47], [3]],
   [',', ',', 'PUNCT', [264, 265], [47], [3]],
   ['quod', 'quod', 'SCONJ', [266, 270], [47], [3]],
   ['substantia', 'substantia', 'NOUN', [271, 281], [47], [3]],
   ['gigneretur', 'gigno', 'VERB', [282, 292], [47], [3, 4]],
   ['ab', 'ab', 'ADP', [293, 295], [47], [4]],
   ['accidenti', 'accidens', 'NOUN', [296, 305], [47], [4]],
   [',', ',', 'PUNCT', [305, 306], [47], [4]],
   ['hec', 'hic', 'DET', [307, 310], [47], [4]],
   ['substantia', 'substantia', 'NOUN', [311, 321], [47], [4]],
   ['non', 'non', 'PART', [322, 325], [47], [4]],
   ['erit', 'sum', 'AUX', [326, 330], [47], [4]],
   ['materia', 'materia', 'NOUN', [331, 338], [47], [4, 5]],
   [',', ',', 'PUNCT', [338, 339], [47], [5]],
   ['quoniam', 'quoniam', 'SCONJ', [340, 347], [47], [5]],
   ['proprium', 'proprius', 'ADJ', [348, 356], [47], [5]],
   ['materiae', 'materia', 'NOUN', [357, 365], [47], [5]],
   ['est', 'sum', 'AUX', [366, 369], [47], [5]],
   ['pari', 'par', 'NOUN', [370, 374], [47], [5]],
   [',', ',', 'PUNCT', [374, 375], [47], [5]],
   ['&', '&', 'PUNCT', [376, 377], [47], [6]],
   ['non', 'non', 'PART', [378, 381], [47], [6]],
   ['agere', 'ago', 'VERB', [382, 387], [47], [6]],
   [',', ',', 'PUNCT', [387, 388], [47], [6]],
   ['ergo', 'ergo', 'ADV', [389, 393], [47], [6]],
   ['si', 'si', 'SCONJ', [394, 396], [47], [6]],
   ['forma', 'forma', 'NOUN', [397, 402], [47], [6]],
   ['erit', 'sum', 'AUX', [403, 407], [47], [6]],
   [',', ',', 'PUNCT', [407, 408], [47], [6]],
   ['nec', 'neque', 'CCONJ', [409, 412], [47], [6]],
   ['abiuncta', 'abiunctus', 'VERB', [413, 421], [47], [6]],
   ['&', '&', 'PUNCT', [422, 423], [47], [7]],
   ['separata', 'separo', 'VERB', [424, 432], [47], [7]],
   [',', ',', 'PUNCT', [432, 433], [47], [7]],
   ['ex', 'ex', 'ADP', [434, 436], [47], [7]],
   ['quo', 'qui', 'PRON', [437, 440], [47], [7]],
   ['alicuius', 'aliquis', 'DET', [441, 449], [47], [7]],
   ['corporis', 'corpus', 'NOUN', [450, 458], [47], [7]],
   ['forma', 'forma', 'NOUN', [459, 464], [47], [7]],
   [',', ',', 'PUNCT', [464, 465], [47], [7]],
   ['quia', 'quia', 'SCONJ', [466, 470], [47], [8]],
   ['corpus', 'corpus', 'NOUN', [471, 477], [47], [8]],
   ['hoc', 'hic', 'DET', [478, 481], [47], [8]],
   ['uniuersa', 'uniuersus', 'DET', [482, 490], [47], [8]],
   ['mineralia', 'mineralis', 'ADJ', [491, 500], [47], [8]],
   ['per', 'per', 'ADP', [501, 504], [47], [8]],
   ['suam', 'suus', 'DET', [505, 509], [47], [8]],
   ['formam', 'forma', 'NOUN', [510, 516], [47], [9]],
   ['gigneret', 'gigno', 'VERB', [517, 525], [47], [9]],
   [',', ',', 'PUNCT', [525, 526], [47], [9]],
   ['quod', 'qui', 'PRON', [527, 531], [47], [9]],
   ['falsum', 'falsum', 'ADJ', [532, 538], [47], [9]],
   ['est', 'sum', 'AUX', [539, 542], [47], [9]],
   [',', ',', 'PUNCT', [542, 543], [47], [9]],
   ['dicamus', 'dico', 'VERB', [544, 551], [47], [9]],
   ['igitur', 'igitur', 'PART', [552, 558], [47], [9, 10]],
   ['calidu', 'calidu', 'VERB', [559, 565], [47], [10]],
   ['&', '&', 'PUNCT', [566, 567], [47], [10]],
   ['frigidum', 'frigidus', 'ADJ', [568, 576], [47], [10]],
   ['tanquam', 'tamquam', 'ADV', [577, 584], [47], [10]],
   ['instrumenta', 'instrumentum', 'NOUN', [585, 596], [47], [10]],
   [',', ',', 'PUNCT', [596, 597], [47], [10]],
   ['cum', 'cum', 'SCONJ', [598, 601], [47], [10]],
   ['uaria', 'uarius', 'ADJ', [602, 607], [47], [11]],
   ['ac', 'atque', 'CCONJ', [608, 610], [47], [11]],
   ['diuersa', 'diuersus', 'ADJ', [611, 618], [47], [11]],
   ['mineralia', 'mineralis', 'ADJ', [619, 628], [47], [11]],
   ['efficiunt', 'efficio', 'VERB', [629, 638], [47], [11]],
   [',', ',', 'PUNCT', [638, 639], [47], [11]],
   ['non', 'non', 'PART', [640, 643], [47], [11]],
   ['nisi', 'nisi', 'SCONJ', [644, 648], [47], [11]],
   ['in', 'in', 'ADP', [649, 651], [47], [12]],
   ['gignentium', 'gigno', 'VERB', [652, 662], [47], [12]],
   ['uirture', 'uirtur', 'NOUN', [663, 670], [47], [12]],
   [',', ',', 'PUNCT', [670, 671], [47], [12]],
   ['que', 'qui', 'PRON', [672, 675], [47], [12]],
   ['eiusdem', 'idem', 'DET', [676, 683], [47], [12]],
   ['speciei', 'species', 'NOUN', [684, 691], [47], [12]],
   ['sunt', 'sum', 'AUX', [692, 696], [47], [13]],
   [',', ',', 'PUNCT', [696, 697], [47], [13]],
   ['cum', 'cum', 'ADP', [698, 701], [47], [13]],
   ['genitis', 'genitus', 'NOUN', [702, 709], [47], [13]],
   ['producunt', 'produco', 'VERB', [710, 719], [47], [13]],
   [',', ',', 'PUNCT', [719, 720], [47], [13]],
   ['quare', 'quare', 'ADV', [721, 726], [47], [13]],
   ['aurum', 'aurum', 'NOUN', [727, 732], [47], [13]],
   ['nisi', 'nisi', 'SCONJ', [733, 737], [47], [13]],
   ['ab', 'ab', 'ADP', [738, 740], [47], [14]],
   ['auro', 'aurum', 'NOUN', [741, 745], [47], [14]],
   [',', ',', 'PUNCT', [745, 746], [47], [14]],
   ['&', '&', 'PUNCT', [747, 748], [47], [14]],
   ['caetera', 'caeterus', 'DET', [749, 756], [47], [14]],
   ['mineralia', 'mineralis', 'ADJ', [757, 766], [47], [14]],
   ['a', 'ab', 'ADP', [767, 768], [47], [14]],
   ['consimilibus', 'consimilis', 'ADJ', [769, 781], [47], [14]],
   ['specie', 'species', 'NOUN', [782, 788], [47], [15]],
   ['producuntur', 'produco', 'VERB', [789, 800], [47], [15]],
   [',', ',', 'PUNCT', [800, 801], [47], [15]],
   ['quod', 'quod', 'SCONJ', [802, 806], [47], [15]],
   ['Alchymiste', 'Alchymiste', 'PROPN', [807, 817], [47], [15]],
   ['comprobant', 'comprobo', 'VERB', [818, 828], [47], [15, 16]],
   [',', ',', 'PUNCT', [828, 829], [47], [16]],
   ['cu', 'cum', 'SCONJ', [830, 832], [47], [16]],
   ['aurum', 'aurum', 'NOUN', [833, 838], [47], [16]],
   ['efficere', 'efficio', 'VERB', [839, 847], [47], [16]],
   ['student', 'studeo', 'VERB', [848, 855], [47], [16]],
   [',', ',', 'PUNCT', [855, 856], [47], [16]],
   ['illud', 'ille', 'DET', [857, 862], [47], [16]],
   ['multis', 'multus', 'DET', [863, 869], [47], [16, 17]],
   ['rebus', 'res', 'NOUN', [870, 875], [47], [17]],
   ['permiscent', 'permisceo', 'VERB', [876, 886], [47], [17]],
   [',', ',', 'PUNCT', [886, 887], [47], [17]],
   ['quod', 'qui', 'PRON', [888, 892], [47], [17]],
   ['quidem', 'quidem', 'PART', [893, 899], [47], [17]],
   ['recta', 'rego', 'ADV', [900, 905], [47], [17]],
   ['cum', 'cum', 'ADP', [906, 909], [47], [17]],
   ['ratione', 'ratio', 'NOUN', [910, 917], [47], [18]],
   ['factum', 'facio', 'VERB', [918, 924], [47], [18]],
   ['est', 'sum', 'AUX', [925, 928], [47], [18]],
   [',', ',', 'PUNCT', [928, 929], [47], [18]],
   ['nam', 'nam', 'PART', [930, 933], [47], [18]],
   ['ea', 'is', 'PRON', [934, 936], [47], [18]],
   ['miscentur', 'misceo', 'VERB', [937, 946], [47], [18]],
   [',', ',', 'PUNCT', [946, 947], [47], [18]],
   ['ut', 'ut', 'SCONJ', [948, 950], [47], [18]],
   ['materiam', 'materia', 'NOUN', [951, 959], [47], [18]],
   ['praeparent', 'praeparo', 'VERB', [960, 970], [47], [19]],
   [',', ',', 'PUNCT', [970, 971], [47], [19]],
   ['atque', 'atque', 'CCONJ', [972, 977], [47], [19]],
   ['afficiant', 'afficio', 'VERB', [978, 987], [47], [19]],
   [',', ',', 'PUNCT', [987, 988], [47], [19]],
   ['que', 'que', 'PRON', [989, 992], [47], [19]],
   ['cum', 'cum', 'SCONJ', [993, 996], [47], [19]],
   ['disposita', 'dispono', 'VERB', [997, 1006], [47], [19]],
   ['est', 'sum', 'AUX', [1007, 1010], [47], [20]],
   [',', ',', 'PUNCT', [1010, 1011], [47], [20]],
   ['tunc', 'tunc', 'ADV', [1012, 1016], [47], [20]],
   ['aurum', 'aurum', 'NOUN', [1017, 1022], [47], [20]],
   ['aurum', 'aurum', 'NOUN', [1023, 1028], [47], [20]],
   ['producere', 'produco', 'VERB', [1029, 1038], [47], [20]],
   ['poterit', 'possum', 'VERB', [1039, 1046], [47], [20]],
   [',', ',', 'PUNCT', [1046, 1047], [47], [20]],
   ['ex', 'ex', 'ADP', [1048, 1050], [47], [20]],
   ['his', 'hic', 'DET', [1051, 1054], [47], [21]],
   ['pater', 'pater', 'NOUN', [1055, 1060], [47], [21]],
   [',', ',', 'PUNCT', [1060, 1061], [47], [21]],
   ['cum', 'cum', 'SCONJ', [1062, 1065], [47], [21]],
   ['aliquid', 'aliquis', 'PRON', [1066, 1073], [47], [21]],
   ['producere', 'produco', 'VERB', [1074, 1083], [47], [21]],
   ['uolumus', 'uolo', 'VERB', [1084, 1091], [47], [21]],
   [',', ',', 'PUNCT', [1091, 1092], [47], [21]],
   ['ut', 'ut', 'SCONJ', [1093, 1095], [47], [22]],
   ['consimilia', 'consimilis', 'DET', [1096, 1106], [47], [22]],
   ['eligamus', 'eligo', 'VERB', [1107, 1115], [47], [22]],
   [',', ',', 'PUNCT', [1115, 1116], [47], [22]],
   ['ut', 'ut', 'SCONJ', [1117, 1119], [47], [22]],
   ['ab', 'ab', 'ADP', [1120, 1122], [47], [22]],
   ['eis', 'is', 'PRON', [1123, 1126], [47], [22]],
   ['perfectius', 'perfectior', 'ADV', [1127, 1137], [47], [22]],
   ['aliquod', 'aliqui', 'DET', [1138, 1145], [47], [23]],
   ['oriri', 'orior', 'VERB', [1146, 1151], [47], [23]],
   ['possit', 'possum', 'VERB', [1152, 1158], [47], [23]],
   [',', ',', 'PUNCT', [1158, 1159], [47], [23]],
   ['postquam', 'postquam', 'SCONJ', [1160, 1168], [47], [23]],
   ['declarauimus', 'declaro', 'VERB', [1169, 1181], [47], [23]],
   ['unde', 'unde', 'ADV', [1182, 1186], [47], [24]],
   ['ortum', 'ortus', 'NOUN', [1187, 1192], [47], [24]],
   ['habeant', 'habeo', 'VERB', [1193, 1200], [47], [24]],
   ['hec', 'hic', 'DET', [1201, 1204], [47], [24]],
   ['omnia', 'omnis', 'DET', [1205, 1210], [47], [24]],
   ['.', '.', 'PUNCT', [1210, 1211], [47], [24]]]],
 [100060,
  1317,
  'Inter caetera quae hominis ingenio perquisita, summo studio cura & diligentia tentata fuerunt, est metallorum generatio, ac praesertim auri & argenti, quae ob miram utilitatem & communem usum, De Metallis. 161 summopere ab hominum multitudine expetuntur, hinc ortum est Alchymiae desiderium, pro qua Arte inuenienda potius quam addiscenda plurimi laborarunt.',
  [['Inter', 'inter', 'ADP', [0, 5], [176], [23]],
   ['caetera', 'caeterus', 'DET', [6, 13], [176], [23]],
   ['quae', 'qui', 'PRON', [14, 18], [176], [23]],
   ['hominis', 'homo', 'NOUN', [19, 26], [176], [23]],
   ['ingenio', 'ingenium', 'NOUN', [27, 34], [176], [23, 24]],
   ['perquisita', 'perquiro', 'VERB', [35, 45], [176], [24]],
   [',', ',', 'PUNCT', [45, 46], [176], [24]],
   ['summo', 'summus', 'ADJ', [47, 52], [176], [24]],
   ['studio', 'studium', 'NOUN', [53, 59], [176], [24]],
   ['cura', 'cura', 'NOUN', [60, 64], [176], [24]],
   ['&', '&', 'PUNCT', [65, 66], [176], [24]],
   ['diligentia', 'diligentia', 'NOUN', [67, 77], [176], [24, 25]],
   ['tentata', 'tento', 'VERB', [78, 85], [176], [25]],
   ['fuerunt', 'sum', 'AUX', [86, 93], [176], [25]],
   [',', ',', 'PUNCT', [93, 94], [176], [25]],
   ['est', 'sum', 'AUX', [95, 98], [176], [25]],
   ['metallorum', 'metallum', 'NOUN', [99, 109], [176], [25]],
   ['generatio', 'generatio', 'NOUN', [110, 119], [176], [25, 26]],
   [',', ',', 'PUNCT', [119, 120], [176], [26]],
   ['ac', 'atque', 'CCONJ', [121, 123], [176], [26]],
   ['praesertim', 'praesertim', 'ADV', [124, 134], [176], [26]],
   ['auri', 'aurum', 'NOUN', [135, 139], [176], [26]],
   ['&', '&', 'PUNCT', [140, 141], [176], [26]],
   ['argenti', 'argentum', 'NOUN', [142, 149], [176], [26]],
   [',', ',', 'PUNCT', [149, 150], [176], [26]],
   ['quae', 'qui', 'PRON', [151, 155], [176], [26]],
   ['ob', 'ob', 'ADP', [156, 158], [176], [27]],
   ['miram', 'mirus', 'ADJ', [159, 164], [176], [27]],
   ['utilitatem', 'utilitas', 'NOUN', [165, 175], [176], [27]],
   ['&', '&', 'PUNCT', [176, 177], [176], [27]],
   ['communem', 'communis', 'ADJ', [178, 186], [176], [27]],
   ['usum', 'usus', 'NOUN', [187, 191], [176], [27]],
   [',', ',', 'PUNCT', [191, 192], [176], [27]],
   ['De', 'de', 'ADP', [193, 195], [177], [0]],
   ['Metallis', 'metallum', 'NOUN', [196, 204], [177], [0]],
   ['.', '.', 'PUNCT', [204, 205], [177], [0]],
   ['161', '161', 'NUM', [206, 209], [177], [0]],
   ['summopere', 'summopere', 'ADV', [210, 219], [177], [1]],
   ['ab', 'ab', 'ADP', [220, 222], [177], [1]],
   ['hominum', 'homo', 'NOUN', [223, 230], [177], [1]],
   ['multitudine', 'multitudo', 'NOUN', [231, 242], [177], [1]],
   ['expetuntur', 'expeto', 'VERB', [243, 253], [177], [1, 2]],
   [',', ',', 'PUNCT', [253, 254], [177], [2]],
   ['hinc', 'hinc', 'ADV', [255, 259], [177], [2]],
   ['ortum', 'orior', 'VERB', [260, 265], [177], [2]],
   ['est', 'sum', 'AUX', [266, 269], [177], [2]],
   ['Alchymiae', 'Alchymia', 'PROPN', [270, 279], [177], [2]],
   ['desiderium', 'desiderium', 'NOUN', [280, 290], [177], [2, 3]],
   [',', ',', 'PUNCT', [290, 291], [177], [3]],
   ['pro', 'pro', 'ADP', [292, 295], [177], [3]],
   ['qua', 'qui', 'PRON', [296, 299], [177], [3]],
   ['Arte', 'Ars', 'NOUN', [300, 304], [177], [3]],
   ['inuenienda', 'inueniendus', 'VERB', [305, 315], [177], [3]],
   ['potius', 'potior', 'ADV', [316, 322], [177], [3]],
   ['quam', 'quam', 'SCONJ', [323, 327], [177], [3]],
   ['addiscenda', 'addisco', 'VERB', [328, 338], [177], [4]],
   ['plurimi', 'multus', 'DET', [339, 346], [177], [4]],
   ['laborarunt', 'laboro', 'VERB', [347, 357], [177], [4]],
   ['.', '.', 'PUNCT', [357, 358], [177], [4]]]],
 [100060,
  1318,
  'Num uero id fecerint ratione recta, & facultate assequendi finem, uel leuiter & inaniter potius, lis adhuc est sub Iudice, nec facile est ueritatem inspicere, propterea consilium & institutum meum est breuibus de Alchymia uerba facere, quam lasonis tempore nonnulli floruisse affirmant, idque satis probabiliter, Uelleris enim aurei nomine intelligi librum uolunt ueterum more in pelle conscriptum, quo auri conficiendi scientia ea arte contineretur, quam Greci Chymiam uocant, Ardua sane Philosophis omnibus uisa est ea quaestio, An metalla inuicem Artis beneficio permutari possint, Ideo uariae extiterunt cum uulgi tum sapientum opiniones, quam ego explicaturus, considerationem uniuersam in quatuor partes distribuam, Agam primo de metallorum generatione, mox rationes nonnullas pro Artis confirmatione referam, Tertio contrariam sententiam comprobabo, Demum aduersa fundamenta euertam. 162 Carerii Quaestio Ordiens igitur (ut sum pollicit,) a metallorum generatione, quoniam tunc arbitramur rem scire;',
  [['Num', 'num', 'PART', [0, 3], [177], [4]],
   ['uero', 'uero', 'ADV', [4, 8], [177], [4]],
   ['id', 'is', 'PRON', [9, 11], [177], [5]],
   ['fecerint', '', 'VERB', [12, 20], [177], [5]],
   ['ratione', 'ratio', 'NOUN', [21, 28], [177], [5]],
   ['recta', 'rego', 'ADJ', [29, 34], [177], [5]],
   [',', ',', 'PUNCT', [34, 35], [177], [5]],
   ['&', '&', 'PUNCT', [36, 37], [177], [5]],
   ['facultate', 'facultas', 'NOUN', [38, 47], [177], [5]],
   ['assequendi', 'assequo', 'VERB', [48, 58], [177], [5, 6]],
   ['finem', 'finis', 'NOUN', [59, 64], [177], [6]],
   [',', ',', 'PUNCT', [64, 65], [177], [6]],
   ['uel', 'uel', 'CCONJ', [66, 69], [177], [6]],
   ['leuiter', 'leuiter', 'ADV', [70, 77], [177], [6]],
   ['&', '&', 'PUNCT', [78, 79], [177], [6]],
   ['inaniter', 'inaniter', 'ADV', [80, 88], [177], [6]],
   ['potius', 'potior', 'ADV', [89, 95], [177], [6]],
   [',', ',', 'PUNCT', [95, 96], [177], [6]],
   ['lis', 'lis', 'NOUN', [97, 100], [177], [7]],
   ['adhuc', 'adhuc', 'ADV', [101, 106], [177], [7]],
   ['est', 'sum', 'AUX', [107, 110], [177], [7]],
   ['sub', 'sub', 'ADP', [111, 114], [177], [7]],
   ['Iudice', 'iudex', 'NOUN', [115, 121], [177], [7]],
   [',', ',', 'PUNCT', [121, 122], [177], [7]],
   ['nec', 'neque', 'CCONJ', [123, 126], [177], [7]],
   ['facile', 'facilis', 'ADJ', [127, 133], [177], [7]],

In [13]:
emlap_tokens = []
for sent_data in emlaps_sents_data:
    sent_len = len(sent_data[2])
    for token_data in sent_data[3]:
        if isinstance(token_data, list) and len(token_data) >= 6:
            emlap_tokens.append({
                "id": sent_data[0],
                "token": token_data[0],
                "lemma": token_data[1],
                "pos": token_data[2],
                "char_position": token_data[3],
                "sent_len": sent_len,  # length of the sentence
                "pdf_page": token_data[4],  # 0-based indexing!
                "pdf_page_textblock": token_data[5]
            })
        else:
            # Optionally log or print the offending entry for inspection
            print("Skipped malformed token_data:", token_data)

In [27]:
emlap_tokens_df = pd.DataFrame(emlap_tokens)

In [28]:
len(emlap_tokens_df)

3495212

In [29]:
emlap_tokens_df["position".head(5)

,id,token,lemma,pos,char_position,sent_len,pdf_page,pdf_page_textblock
0,100044,rum,rus,NOUN,"[0, 3]",42,[3],[4]
1,100044,omnium,omnis,DET,"[4, 10]",42,[3],[4]
2,100044,",",",",PUNCT,"[10, 11]",42,[3],[4]
3,100044,in,in,ADP,"[12, 14]",42,[3],[4]
4,100044,uniuersum,uniuersus,DET,"[15, 24]",42,[3],[4]

In [27]:
)#%%
# read back
emlap_tokens_df = pd.read_parquet("../data/emlap_tokens_df.parquet")

SyntaxError: unmatched ')' (1989639051.py, line 1)

In [15]:
emlap_id_filename_dict

{100001: 'Augurello,_Giovanni_Aurelio_-_Chrysopoeia__Venice_1515_pdf.pdf',
 100002: 'Pseudo-Lull1518_De_secretis_naturae_MDZ.pdf',
 100003: 'Pantheus1518_Ars_Transmutationis_Metallicae_BL_GB.pdf',
 100004: 'Pantheus1519_Commentarium_Transmutationis_Metallicae_MDZ.pdf',
 100005: 'Pantheus1530_Voarchadumia_ONB.pdf',
 100006: 'Savonarola1532_De_arte_conficiendi_aquam_vitae_ONB.pdf',
 100007: 'Anon1550_Rosarium_philosophorum_Erara.pdf',
 100008: 'Severinus1572_Epistola_MBZ_MBS.pdf',
 100009: 'Vegius1518_Inter_inferiora_corpora_disputatio_ONB.pdf',
 100010: 'Bracesco1548_De_alchemia_dialogi_II_IA_Madrid.pdf',
 100011: 'De_alchemia1541_MDZ_MBS.pdf',
 100012: 'Gessner1552_Thesaurus_Euonymi_Philiatri_ER_ZZ.pdf',
 100013: 'Ulstad1525_Coelum_philosophorum_IA_BIUSP_pdf.pdf',
 100014: 'Toxites1567_Spongia_stibii_MDZ_MBS.pdf',
 100015: 'Gessner1569_Thesaurus_Euonymi_Philiatri_Liber_Secundus_MDZ_MBS.pdf',
 100016: 'Bonus1546_Pretiosa_Margarita_Novella_ONB.pdf',
 100017: 'Bodenstein1559_Isagoge_MDZ_MBS.pdf',
 100018: 'Trevisanus1567_De_alchemia_MDZ_MBS.pdf',
 100019: 'Ulstadt1526_De_epidemia_ONB.pdf',
 100020: 'Dorn1569_Artificii_chymistici_MDZ_MBS.pdf',
 100021: 'Dorn1567_Clavis_totius_philosophiae_chymisticae_ONB_pdf.pdf',
 100022: 'Anon1550_De_alchemia_opuscula_MDZ_MBS.pdf',
 100023: 'Paracelsus1553_Labyrinthus_medicorum_errantium_MDZ_MBS_pdf.pdf',
 100024: 'Fanianus1560_De_arte_metallicae_ONB_pdf.pdf',
 100025: 'Pseudo-Lull1563_Codicillus_MDZ_MBS_pdf.pdf',
 100026: 'Garlandius1560_Compendium_Alchemiae_SLUB_pdf.pdf',
 100027: 'Pseudo-Paracelsus1568_Pyrophilia_vexationumque_ONB.pdf',
 100028: 'Pedemontanus1563_De_Secretis_MDZ_MBS.pdf',
 100029: 'Paracelsus1560_Libri_quatuor_de_vita_longa_MDZ_MBS.pdf',
 100030: 'Rupescissa1561_De_Consideratione_Quintae_essentie_rerum_GB.pdf',
 100031: 'Phaedro1562_Aquila_coelestis_MBZ_MBS.pdf',
 100032: 'Ventura1571_De_ratione_conficiendi_lapis_MBZ_MBS.pdf',
 100033: 'Paracelsus1582_Centum_quindecim_curationes_MDZ_MBS.pdf',
 100034: 'Penotus1594_Tractatus_varii_MDZ_MBS.pdf',
 100035: 'Dorn1570_Lapis_metaphysicus_MDZ_MBS_pdf.pdf',
 100036: 'Vadis1595_Dialogus_IA_Wellcome.pdf',
 100037: 'DuChesne1575_Ad_Iacobi_Auberti_MDZ_Augsburg.pdf',
 100038: 'Auriferae_artisI1572_MBZ_Augsburg.pdf',
 100039: 'Pseudo-Democritus1572_Ars_magna.pdf',
 100040: 'Pseudo-Lull1567_Mercuriorum_liber_MDZ_MBS.pdf',
 100041: 'Senior1560_De_chemia_senioris_MDZ_MBS.pdf',
 100042: 'Pseudo-Paracelsus1568_De_summis_naturae_mysteriis_MDZ_MBS.pdf',
 100043: 'DuChesne1575_Sclopetarius_MDZ_Augsburg.pdf',
 100044: 'Dorn1578_Theophrasti_Germani_Principis_MDZ_MBS.pdf',
 100045: 'Dorn1583_De_Naturae_luce_physica_MDZ_MBS.pdf',
 100046: 'Dorn1584_Commentaria_in_Archidoxorum_MDZ_MBS.pdf',
 100047: 'Portaleone1584_De_auro_dialogi_tres_ONB.pdf',
 100048: 'Pseudo-Aquinas1579_Secreta_alchemiae_magnalia_ONB.pdf',
 100049: 'Rossi1585_De_destillatione_MDZ_MBS.pdf',
 100050: 'Barnaud1599_Quadriga_aurifera_IA_Madrid.pdf',
 100051: 'Ruland1564_Medicina_practica_recens_MDZ_MDS.pdf',
 100052: 'Khunrath1599_Confessio_de_chao_chymicorum_MDZ_MBS.pdf',
 100053: 'Mirandola1586_De_auro_libri_tres_MDZ_MBS.pdf',
 100054: 'Moffett_De_iure_et_praestantia_MDZ_MBS.pdf',
 100055: 'Erastus1578_Disputatio_de_auro_potabili_MDZ_MBS.pdf',
 100056: 'Claveus1598_Apologia_crysopoeiae_MDZ_MBS.pdf',
 100057: 'Hagecius1585_De_cervisia_ejusque_conficiendi_ratione.pdf',
 100058: 'Hagecius1596_Actio_medica_ER_UBB.pdf',
 100059: 'Suavius1567_Theophrasti_Paracelsi_Philosophiae_ONB.pdf',
 100060: 'Witestein1583_Disceptatio_philosophica_MDZ_MBS.pdf',
 100061: 'Moffett1588_Nosomantica_Hippocrates_ONB.pdf',
 100062: 'Albertus1569_De_concordantia_Hippocraticorum_et_Paracelsistarum_MDZ_MBS.pdf',
 100063: 'Libavius1595_Rerum_chymicarum_epistolica_liber_primus_MDZ_MBS.pdf',
 100064: 'Trevisanus1583_De_chymico_miraculo_MDZ_MBS.pdf',
 100065: 'Libavius1594_Neoparacelsica_MDZ_MBS.pdf',
 100066: 'Suchten1575_De_secretis_antimonii_ONB.pdf',
 100067: 'Wecker1582_De_secretis_ONB.pdf',
 100068: 'Pseudo-Paracelsus1577_Aurora_Thesaurusque_Philosophorum_ONB.pdf',
 100069: 'Severinus1571_Idea_medicinae_MDZ_MBS.pdf',
 100070: 'Libavius,_Andreas_-_Alchemia_Libavii__Frankfurt_am_Main_1597.pdf',
 100071: 'Pseudo-Lull1566_Testamentum_MDZ_MBS.pdf',
 100072: 'Andernach1571_De_medicina_veteri_et_novi_MDZ_MBS.pdf',
 100073: 'Greverus1599_Secretum_MDZ_MBS.pdf',
 100074: 'Hoghelande1595_De_lapidis_physici_conditionibus_MDZ_MBS.pdf',
 100075: 'Dorn1581_Fasciculus_Paracelsicae_MDZ_MBS.pdf'}

In [16]:
position_files_dict = {}
for id, fn in emlap_id_filename_dict.items():
    position_files_dict[id] = fn.replace(".pdf", "_recalculated.json")

In [19]:
# checking whether we have the right files:
textblocks_path = "../data/emlap_annotated_textblocks/"
textblocks_fns =     os.listdir(textblocks_path)

for id, fn in position_files_dict.items():
    if fn in textblocks_fns:
        print(fn)

Augurello,_Giovanni_Aurelio_-_Chrysopoeia__Venice_1515_pdf_recalculated.json
Pseudo-Lull1518_De_secretis_naturae_MDZ_recalculated.json
Pantheus1518_Ars_Transmutationis_Metallicae_BL_GB_recalculated.json
Pantheus1519_Commentarium_Transmutationis_Metallicae_MDZ_recalculated.json
Pantheus1530_Voarchadumia_ONB_recalculated.json
Savonarola1532_De_arte_conficiendi_aquam_vitae_ONB_recalculated.json
Anon1550_Rosarium_philosophorum_Erara_recalculated.json
Severinus1572_Epistola_MBZ_MBS_recalculated.json
Vegius1518_Inter_inferiora_corpora_disputatio_ONB_recalculated.json
Bracesco1548_De_alchemia_dialogi_II_IA_Madrid_recalculated.json
De_alchemia1541_MDZ_MBS_recalculated.json
Gessner1552_Thesaurus_Euonymi_Philiatri_ER_ZZ_recalculated.json
Ulstad1525_Coelum_philosophorum_IA_BIUSP_pdf_recalculated.json
Toxites1567_Spongia_stibii_MDZ_MBS_recalculated.json
Gessner1569_Thesaurus_Euonymi_Philiatri_Liber_Secundus_MDZ_MBS_recalculated.json
Bonus1546_Pretiosa_Margarita_Novella_ONB_recalculated.json
Bodenstein1559_Isagoge_MDZ_MBS_recalculated.json
Trevisanus1567_De_alchemia_MDZ_MBS_recalculated.json
Ulstadt1526_De_epidemia_ONB_recalculated.json
Dorn1569_Artificii_chymistici_MDZ_MBS_recalculated.json
Dorn1567_Clavis_totius_philosophiae_chymisticae_ONB_pdf_recalculated.json
Anon1550_De_alchemia_opuscula_MDZ_MBS_recalculated.json
Paracelsus1553_Labyrinthus_medicorum_errantium_MDZ_MBS_pdf_recalculated.json
Fanianus1560_De_arte_metallicae_ONB_pdf_recalculated.json
Pseudo-Lull1563_Codicillus_MDZ_MBS_pdf_recalculated.json
Garlandius1560_Compendium_Alchemiae_SLUB_pdf_recalculated.json
Pseudo-Paracelsus1568_Pyrophilia_vexationumque_ONB_recalculated.json
Pedemontanus1563_De_Secretis_MDZ_MBS_recalculated.json
Paracelsus1560_Libri_quatuor_de_vita_longa_MDZ_MBS_recalculated.json
Rupescissa1561_De_Consideratione_Quintae_essentie_rerum_GB_recalculated.json
Phaedro1562_Aquila_coelestis_MBZ_MBS_recalculated.json
Ventura1571_De_ratione_conficiendi_lapis_MBZ_MBS_recalculated.json
Paracelsus1582_Centum_quindecim_curationes_MDZ_MBS_recalculated.json
Penotus1594_Tractatus_varii_MDZ_MBS_recalculated.json
Dorn1570_Lapis_metaphysicus_MDZ_MBS_pdf_recalculated.json
Vadis1595_Dialogus_IA_Wellcome_recalculated.json
DuChesne1575_Ad_Iacobi_Auberti_MDZ_Augsburg_recalculated.json
Auriferae_artisI1572_MBZ_Augsburg_recalculated.json
Pseudo-Democritus1572_Ars_magna_recalculated.json
Pseudo-Lull1567_Mercuriorum_liber_MDZ_MBS_recalculated.json
Senior1560_De_chemia_senioris_MDZ_MBS_recalculated.json
Pseudo-Paracelsus1568_De_summis_naturae_mysteriis_MDZ_MBS_recalculated.json
DuChesne1575_Sclopetarius_MDZ_Augsburg_recalculated.json
Dorn1578_Theophrasti_Germani_Principis_MDZ_MBS_recalculated.json
Dorn1583_De_Naturae_luce_physica_MDZ_MBS_recalculated.json
Dorn1584_Commentaria_in_Archidoxorum_MDZ_MBS_recalculated.json
Portaleone1584_De_auro_dialogi_tres_ONB_recalculated.json
Pseudo-Aquinas1579_Secreta_alchemiae_magnalia_ONB_recalculated.json
Rossi1585_De_destillatione_MDZ_MBS_recalculated.json
Barnaud1599_Quadriga_aurifera_IA_Madrid_recalculated.json
Ruland1564_Medicina_practica_recens_MDZ_MDS_recalculated.json
Khunrath1599_Confessio_de_chao_chymicorum_MDZ_MBS_recalculated.json
Mirandola1586_De_auro_libri_tres_MDZ_MBS_recalculated.json
Moffett_De_iure_et_praestantia_MDZ_MBS_recalculated.json
Erastus1578_Disputatio_de_auro_potabili_MDZ_MBS_recalculated.json
Claveus1598_Apologia_crysopoeiae_MDZ_MBS_recalculated.json
Hagecius1585_De_cervisia_ejusque_conficiendi_ratione_recalculated.json
Hagecius1596_Actio_medica_ER_UBB_recalculated.json
Suavius1567_Theophrasti_Paracelsi_Philosophiae_ONB_recalculated.json
Witestein1583_Disceptatio_philosophica_MDZ_MBS_recalculated.json
Moffett1588_Nosomantica_Hippocrates_ONB_recalculated.json
Albertus1569_De_concordantia_Hippocraticorum_et_Paracelsistarum_MDZ_MBS_recalculated.json
Libavius1595_Rerum_chymicarum_epistolica_liber_primus_MDZ_MBS_recalculated.json
Trevisanus1583_De_chymico_miraculo_MDZ_MBS_recalculated.json
Libavius1594_Neoparacelsica_MDZ_MBS_recalculated.json
Suchten1575_De_secretis_antimonii_ONB_recalculated.json
Wecker1582_De_secretis_ONB_recalculated.json
Pseudo-Paracelsus1577_Aurora_Thesaurusque_Philosophorum_ONB_recalculated.json
Severinus1571_Idea_medicinae_MDZ_MBS_recalculated.json
Libavius,_Andreas_-_Alchemia_Libavii__Frankfurt_am_Main_1597_recalculated.json
Pseudo-Lull1566_Testamentum_MDZ_MBS_recalculated.json
Andernach1571_De_medicina_veteri_et_novi_MDZ_MBS_recalculated.json
Greverus1599_Secretum_MDZ_MBS_recalculated.json
Hoghelande1595_De_lapidis_physici_conditionibus_MDZ_MBS_recalculated.json
Dorn1581_Fasciculus_Paracelsicae_MDZ_MBS_recalculated.json

In [37]:
print(emlap_tokens_df.head(5))

       id      token      lemma    pos char_position  sent_len pdf_page  \
0  100044        rum        rus   NOUN        [0, 3]        42      [3]
1  100044     omnium      omnis    DET       [4, 10]        42      [3]
2  100044          ,          ,  PUNCT      [10, 11]        42      [3]
3  100044         in         in    ADP      [12, 14]        42      [3]
4  100044  uniuersum  uniuersus    DET      [15, 24]        42      [3]

  pdf_page_textblock
0                [4]
1                [4]
2                [4]
3                [4]
4                [4]

In [20]:
positions_data_dict = {}
for id, fn in position_files_dict.items():
    with open(textblocks_path + fn, "rb") as f:
        positions_data_dict[id] = json.load(f)

In [34]:
print(positions_data_dict[100044][3])

[{'coordinates': {'upper_left_x': 0.28840337160254725, 'upper_left_y': 0.05273157966958089, 'lower_right_x': 0.6172558183429622, 'lower_right_y': 0.05843229135255066}, 'text': 'THEOPHRASTI\n', 'tag': 'title'}, {'coordinates': {'upper_left_x': 0.1556974779657957, 'upper_left_y': 0.10634677370483689, 'lower_right_x': 0.6815255814239758, 'lower_right_y': 0.11219000193398809}, 'text': 'GERMANI\n', 'tag': 'title'}, {'coordinates': {'upper_left_x': 0.17183192918280593, 'upper_left_y': 0.14593821183519523, 'lower_right_x': 0.7185922318146009, 'lower_right_y': 0.15163891898764567}, 'text': 'PARACELSI, MEDICO¬\n', 'tag': 'title'}, {'coordinates': {'upper_left_x': 0.21216806363658744, 'upper_left_y': 0.1790023767466783, 'lower_right_x': 0.6818286030232406, 'lower_right_y': 0.18470309296016738}, 'text': 'RVM ET PHILOSOPHO¬\n', 'tag': 'title'}, {'coordinates': {'upper_left_x': 0.24484032382484244, 'upper_left_y': 0.20411399424500817, 'lower_right_x': 0.6592873453092174, 'lower_right_y': 0.20995722247415938}, 'text': 'rum omnium, in vniuersum\n', 'tag': 'text'}, {'coordinates': {'upper_left_x': 0.3339831953289128, 'upper_left_y': 0.23005219593184012, 'lower_right_x': 0.5809196408055409, 'lower_right_y': 0.23589542416099132}, 'text': 'facilè Principis.\n', 'tag': 'text'}, {'coordinates': {'upper_left_x': 0.16779831317292543, 'upper_left_y': 0.26422804155145857, 'lower_right_x': 0.7344695275571166, 'lower_right_y': 0.2699287577649477}, 'text': 'De restituta vtriusque Medicinae vera\n', 'tag': 'text'}, {'coordinates': {'upper_left_x': 0.39973108628216913, 'upper_left_y': 0.29931586258768184, 'lower_right_x': 0.5114101890756303, 'lower_right_y': 0.30515910893891035}, 'text': 'Praxi.\n', 'tag': 'text'}, {'coordinates': {'upper_left_x': 0.2617815033728335, 'upper_left_y': 0.3343752682067436, 'lower_right_x': 0.6394679478236607, 'lower_right_y': 0.3402185145579721}, 'text': 'LIBER PRIMVS.\n', 'tag': 'title'}, {'coordinates': {'upper_left_x': 0.13956302674878546, 'upper_left_y': 0.36570072853650165, 'lower_right_x': 0.7605386173023897, 'lower_right_y': 0.3714014266279134}, 'text': 'Gerardo Dorn Doctore Physico, ac interprete Ger¬\n', 'tag': 'text'}, {'coordinates': {'upper_left_x': 0.224268911666229, 'upper_left_y': 0.3902137738225579, 'lower_right_x': 0.6722984506302521, 'lower_right_y': 0.3959144719139697}, 'text': 'manico, in hunc ordinem recolligente.\n', 'tag': 'text'}, {'coordinates': {'upper_left_x': 0.1411764705882353, 'upper_left_y': 0.4155819274467414, 'lower_right_x': 0.755849835051208, 'lower_right_y': 0.4212826255381532}, 'text': 'Ad Illustriss. ac Potentiss. Prin cip. D. FRANCISC.\n', 'tag': 'text'}, {'coordinates': {'upper_left_x': 0.1778823467863708, 'upper_left_y': 0.43524938297951304, 'lower_right_x': 0.7272080878249737, 'lower_right_y': 0.44095008107092487}, 'text': 'VALESIVM, Andegauorum, Biturigum,\n', 'tag': 'text'}, {'coordinates': {'upper_left_x': 0.2210420239873293, 'upper_left_y': 0.4543752783551069, 'lower_right_x': 0.6760516511292017, 'lower_right_y': 0.46021852470633534}, 'text': 'Alenconium, Turonensium, &c. Ducem.\n', 'tag': 'text'}, {'coordinates': {'upper_left_x': 0.21700970305114234, 'upper_left_y': 0.5693468832346719, 'lower_right_x': 0.21950681029247637, 'lower_right_y': 0.6215397705658031}, 'text': 'ALTERIUS NON SIT\n', 'tag': 'text'}, {'coordinates': {'upper_left_x': 0.6559748801864496, 'upper_left_y': 0.5731446544801254, 'lower_right_x': 0.6578349137506565, 'lower_right_y': 0.6353635810616464}, 'text': 'QUI SVVS ESSE POTEST\n', 'tag': 'text'}, {'coordinates': {'upper_left_x': 0.3073613527442227, 'upper_left_y': 0.8080759660082022, 'lower_right_x': 0.5871260955554096, 'lower_right_y': 0.8137767365879232}, 'text': 'LVGDVNI,\n', 'tag': 'title'}, {'coordinates': {'upper_left_x': 0.21499159356125264, 'upper_left_y': 0.8342991917263584, 'lower_right_x': 0.6785677356880252, 'lower_right_y': 0.8399999623060793}, 'text': 'PRO IACOBO DV PVYS.\n', 'tag': 'title'}, {'coordinates': {'upper_left_x': 0.300504206809677, 'upper_left_y': 0.8727790306979291, 'lower_right_x': 0.6031016117384453, 'lower_right_y': 0.8784798012776499}, 'text': 'M. D. LXXVIII.\n', 'tag': 'title'}, {'coordinates': {'upper_left_x': 0.14884033203125, 'upper_left_y': 0.899857400998367, 'lower_right_x': 0.7594378815979517, 'lower_right_y': 0.9055581715780879}, 'text': 'Cum priuileg. Caesareae ac Regiae maiest. ad decennium.\n', 'tag': 'text'}]

In [52]:
import numpy as np
import pandas as pd

def _flat_int_list(x):
    # turn scalars/arrays/Series/[arrays] into a flat list of ints
    if isinstance(x, (list, tuple)):
        seq = x
    elif isinstance(x, (np.ndarray, pd.Series)):
        seq = x.tolist()
    else:
        seq = [x]
    out = []
    for v in seq:
        if isinstance(v, (list, tuple, np.ndarray, pd.Series)):
            out.extend([int(i) for i in np.array(v).flatten().tolist()])
        else:
            out.append(int(v))
    return out

def get_positions(row):
    data = positions_data_dict[row["id"]]          # e.g. positions_data_dict[100044]
    pages  = _flat_int_list(row["pdf_page"])
    blocks = _flat_int_list(row["pdf_page_textblock"])

    # one page, many blocks → repeat page
    if len(pages) == 1 and len(blocks) > 1:
        pages = pages * len(blocks)

    out = []
    for p, b in zip(pages, blocks):
        page_blocks = data[p]                      # list of blocks on this page
        # simple 1-based fallback if needed
        if b >= len(page_blocks) and b > 0:
            b = b - 1
        # final guard: skip if still OOB
        if 0 <= b < len(page_blocks):
            out_el = page_blocks[b]
            out_el["page"] = p
            out.append(out_el)
        # else: silently skip (or append None if you prefer)
    return out

# apply
emlap_tokens_df["positions"] = emlap_tokens_df.apply(get_positions, axis=1)

In [53]:
emlap_tokens_df.sample(100).to_csv("../data/positions_full_sample.csv")

In [54]:
emlap_tokens_df.to_parquet("../data/emlap_tokens_positions_df.parquet")

In [30]:
# a sanity check
emlap_tokens_df[emlap_tokens_df["lemma"].str.contains("alchy")].head(30)

,id,token,lemma,pos,char_position,sent_len,pdf_page,pdf_page_textblock
76404,100034,Alchymia,alchymia,PROPN,"[52, 60]",67,[77],[22]
81331,100034,alchymistarum,alchymista,DET,"[36, 49]",58,[106],"[19, 20]"
137230,100060,alchymica,alchymicus,ADJ,"[131, 140]",252,[150],[23]
142127,100060,Alchymia,alchymia,PROPN,"[213, 221]",1006,[177],[9]
146721,100060,Alchymiam,alchymia,PROPN,"[595, 604]",834,[200],[30]
148404,100060,Alchymia,alchymia,PROPN,"[48, 56]",1369,[209],[6]
148430,100060,Alchymia,alchymia,PROPN,"[229, 237]",1369,[209],[11]
149967,100060,Alchymiam,alchymia,PROPN,"[145, 154]",1212,[216],[31]
150353,100060,Alchymiam,alchymia,PROPN,"[101, 110]",528,[218],[26]
150373,100060,Alchymia,alchymia,PROPN,"[216, 224]",528,[219],[1]
150445,100060,Alchymiam,alchymia,PROPN,"[48, 57]",384,[219],[11]
153695,100060,Alchymiam,alchymia,PROPN,"[995, 1004]",2005,[235],"[15, 16]"
153802,100060,Alchymiam,alchymia,PROPN,"[1653, 1662]",2005,[236],[3]
153808,100060,Alchymiam,alchymia,PROPN,"[1692, 1701]",2005,[236],[4]
296627,100012,alchymiam,alchymia,NOUN,"[30, 39]",206,[7],[13]
296871,100012,alchymia,alchymia,NOUN,"[19, 27]",63,[9],[6]
296979,100012,alchymia,alchymia,NOUN,"[146, 154]",229,[9],"[23, 24]"
301241,100012,alchymistam,alchymista,NOUN,"[5, 16]",217,[38],[19]
307908,100012,alchymiste,alchymista,NOUN,"[28, 38]",72,[83],[8]
348953,100012,alchymistarum,alchymista,VERB,"[143, 156]",234,[351],[23]
364105,100012,alchymistarum,alchymista,VERB,"[66, 79]",128,[450],"[5, 6]"
366326,100012,alchymistae,alchymista,NOUN,"[12, 23]",24,[464],"[19, 20]"
366431,100012,alchymista,alchymista,NOUN,"[56, 66]",81,[465],[10]
368262,100012,alchymicis,alchymicus,NOUN,"[23, 33]",135,[477],[6]
368326,100012,alchymicis,alchymicus,NOUN,"[22, 32]",56,[477],[17]
384565,100012,alchymicis,alchymicus,NOUN,"[23, 33]",141,[585],"[8, 9]"
403503,100025,Alchymistarum,alchymista,PROPN,"[149, 162]",214,[104],[17]
409281,100025,Alchymistarum,alchymista,PROPN,"[32, 45]",119,[151],[5]
413548,100025,Alchymista,alchymista,PROPN,"[26, 36]",80,[186],"[10, 11]"
416440,100025,Alchymicorum,alchymicus,PROPN,"[160, 172]",280,[211],"[1, 2]"

In [33]:
emlap_lemma_counts = pd.DataFrame(emlap_tokens_df[emlap_tokens_df["pos"].isin(["NOUN", "VERB", "ADJ", "PROPN"])].value_counts("lemma"))

In [34]:
len(emlap_lemma_counts)

66927

In [35]:
emlap_lemma_counts.head(5)

        count
lemma
        22091
aqua    19987
facio   16031
possum  14364
dico    14091

In [36]:
emlap_lemma_counts.reset_index(inplace=True)

In [37]:
emlap_lemma_counts[emlap_lemma_counts["lemma"].str.startswith("alch")]

               lemma  count
811         alchimia    319
2324        alchymia     91
2789      alchimista     72
3319      alchymista     56
3644        alchemia     50
3914      alchimicus     44
4497      alchymicus     36
4725       alchimius     34
8508      alchemista     13
10659  alchimisticus      9
11452       alchalis      8
13652     alchimilla      6
15076    alchimistas      5
17423      alchimizo      4
25784  alchimistarum      2
25785      alchimiae      2
25786     alchimicum      2
25787        alcharo      2
25788     alchemicus      2
25791      alchahsum      2
25793      alchimiso      2
25849        alchoos      2
25850  alchumisticus      2
25851       alchitra      2
48047      alchymiae      1
48048      alchymius      1
48049      alchymizo      1
48056   alchimistrus      1
48057    alchimistus      1
48058     alchimstum      1
48059       alchimuc      1
48060      alchitran      1
48061         alchum      1
48062     alchumista      1
48079    alchimichus      1
48080       alchimie      1
48081    alchimillus      1
48082    alchimistar      1
48083     alchimiste      1
48087        alchems      1
48088       alchermo      1
48089      alchi'mia      1
48090    alchi'micus      1
48091      alchichil      1
48092      alchifeco      1
48093        alchilo      1
48094      alchimica      1
48099          alche      1
48100    alchechengo      1
48101       alchemie      1
48102     alchemieus      1