In [1]:
import pandas as pd
import os
import json
import spacy
import re

In [2]:
source_path = "../data/sents_data_jsons_dicts/"
filenames = os.listdir(source_path)

In [3]:
len(filenames)

100

In [4]:
emlap_tokens = []
for filename in filenames:
    f_sents_data = json.load(open(source_path + filename, "rb"))
    for sent_data in f_sents_data:
        sent_len = len(sent_data["sent_text"])
        for token_data in sent_data["tokens_data"]:
            token_data["id"] = sent_data["work_id"]
            token_data["sent_idx"] = sent_data["sent_id"]
            token_data["sent_len"] = sent_len
            emlap_tokens.append(token_data)

In [5]:
len(emlap_tokens)

6477016

In [6]:
emlap_tokens_df = pd.DataFrame(emlap_tokens)

In [7]:
for attr in ["page", "textblock", "tag", "blocktype"]:
    emlap_tokens_df[attr] = emlap_tokens_df.apply(lambda row: row["ref"][attr], axis=1)

In [10]:
emlap_tokens_df.shape

(6477016, 13)

In [14]:
emlap_tokens_df[emlap_tokens_df["pos"]=="PROPN"]["lemma"].value_counts()

lemma
Mercurius      4769
Deus           3352
philosophus    1797
Galenus        1266
Aristoteles    1249
               ...
uria              1
Dan¬              1
dan               1
spithama          1
hyrcanus          1
Name: count, Length: 22648, dtype: int64

In [15]:
emlap_tokens_df["pos"].value_counts()

pos
PUNCT    1434275
NOUN     1358905
VERB      915291
ADJ       489283
ADP       431607
ADV       396326
DET       330822
PRON      235866
SCONJ     204660
CCONJ     171060
AUX       157958
PROPN     141078
PART      113359
NUM        77330
SYM         8670
X           6592
INTJ        3934
Name: count, dtype: int64

In [19]:
emlap_tokens_df[emlap_tokens_df["lemma"]=="mercurius"]

,token_text,lemma,pos,ref,char_start,char_end,id,sent_idx,sent_len,page,textblock,tag,blocktype
2594,mercurium,mercurius,NOUN,"{'blocktype': 'text', 'page': [15], 'tag': '',...",13,22,100044,131,30,[15],[2],,text
4203,mercurium,mercurius,NOUN,"{'blocktype': 'text', 'page': [20], 'tag': '',...",33,42,100044,478,70,[20],"[11, 12]",,text
6207,mercurii,mercurius,ADJ,"{'blocktype': 'text', 'page': [31], 'tag': '',...",10,18,100044,787,45,[31],[2],,text
6305,mercurii,mercurius,ADJ,"{'blocktype': 'text', 'page': [31], 'tag': '',...",8,16,100044,792,23,[31],[15],,text
6354,mercurium,mercurius,NOUN,"{'blocktype': 'text', 'page': [31], 'tag': '',...",21,30,100044,797,74,[31],[22],,text
...,...,...,...,...,...,...,...,...,...,...,...,...,...
6337868,mercurii,mercurius,ADJ,"{'blocktype': 'text', 'page': [113], 'tag': ''...",118,126,100022,1040,552,[113],[27],,text
6341916,mercurium,mercurius,NOUN,"{'blocktype': 'text', 'page': [131], 'tag': ''...",85,94,100022,1191,493,[131],[27],,text
6382979,mercurii,mercurius,ADJ,"{'blocktype': 'text', 'page': [327], 'tag': ''...",66,74,100022,3203,105,[327],[26],,text
6447078,mercurio,mercurius,NOUN,"{'blocktype': 'text', 'page': [275], 'tag': ''...",19,27,100011,3550,75,[275],"[7, 8]",,text
6465998,Mercurius,mercurius,NOUN,"{'blocktype': 'text', 'page': [351], 'tag': ''...",0,9,100011,4467,46,[351],[8],,text

In [11]:
emlap_tokens_df[emlap_tokens_df["pos"]=="SYM"]["lemma"].value_counts()

lemma
y          2989
recipe     1464
z          1422
lb          936
scr         288
           ...
male          1
recipie       1
zs i          1
o             1
aster         1
Name: count, Length: 134, dtype: int64

In [20]:
emlap_tokens_df["id"].value_counts()

id
100100    535117
100085    394698
100004    368660
100072    341460
100038    261776
           ...
100052      5358
100099      4512
100014      2646
100031      2489
100008      2261
Name: count, Length: 100, dtype: int64

In [21]:
emlap_tokens_df.to_parquet("../data/emlap_corpus_public/emlap_tokens_df.parquet")

## Update metadata table

In [2]:
emlap_tokens_df = pd.read_parquet("../data/emlap_corpus_public/emlap_tokens_df.parquet")

In [5]:
emlap_tokens_df.head(5)

,token_text,lemma,pos,ref,char_start,char_end,id,sent_idx,sent_len,page,textblock,tag,blocktype
0,Germani,Germani,PROPN,"{'blocktype': 'text', 'page': [3], 'tag': '', ...",0,7,100044,0,7,[3],[1],,text
1,Paracelsi,Paracelsi,NOUN,"{'blocktype': 'title', 'page': [3], 'tag': '',...",0,9,100044,1,23,[3],[2],,title
2,",",",",PUNCT,"{'blocktype': 'title', 'page': [3], 'tag': '',...",9,10,100044,1,23,[3],[2],,title
3,Medicorum,medicus,NOUN,"{'blocktype': 'title', 'page': [3], 'tag': '',...",11,20,100044,1,23,[3],"[2, 3]",,title
4,Et,et,CCONJ,"{'blocktype': 'title', 'page': [3], 'tag': '',...",21,23,100044,1,23,[3],[3],,title

In [14]:
emlap_tokens_df[emlap_tokens_df["tag"]=="GR"]

,token_text,lemma,pos,ref,char_start,char_end,id,sent_idx,sent_len,page,textblock,tag,blocktype
6919,β,ἐὕω,VERB,"{'blocktype': 'text', 'page': [34], 'tag': 'GR...",0,1,100044,886,2,[34],[20],GR,text
44380,β,ἐὕω,VERB,"{'blocktype': 'text', 'page': [227], 'tag': 'G...",0,1,100044,6604,2,[227],[10],GR,text
51950,additionae?β,additionae?β,PROPN,"{'blocktype': 'text', 'page': [269], 'tag': 'G...",122,134,100044,7916,135,[269],"[10, 11]",GR,text
102820,Δρέπων,Δρέπων,PROPN,"{'blocktype': 'text', 'page': [9], 'tag': 'GR'...",0,6,100094,29,251,[9],[9],GR,text
102821,τὰς,ὁ,DET,"{'blocktype': 'text', 'page': [9], 'tag': 'GR'...",7,10,100094,29,251,[9],[9],GR,text
...,...,...,...,...,...,...,...,...,...,...,...,...,...
6473960,Περὶ,περί,ADP,"{'blocktype': 'text', 'page': [384], 'tag': 'G...",102,106,100011,4834,115,[384],[3],GR,text
6473961,χημείας,χῆμεια,NOUN,"{'blocktype': 'text', 'page': [384], 'tag': 'G...",107,114,100011,4834,115,[384],[3],GR,text
6476023,χρυσοποιία,χρυσοποιία,NOUN,"{'blocktype': 'text', 'page': [394], 'tag': 'G...",82,92,100011,4986,239,[394],[3],GR,text
6477002,Σ,Σ,INTJ,"{'blocktype': 'title', 'page': [400], 'tag': '...",11,12,100011,5192,12,[400],[11],GR,title
6477007,οθ,οθ,INTJ,"{'blocktype': 'text', 'page': [400], 'tag': 'G...",29,31,100011,5193,59,[400],[13],GR,text

In [17]:
len(emlap_tokens_df[emlap_tokens_df["pos"]=="SYM"].value_counts("lemma"))

134

In [18]:
emlap_tokens_df.value_counts("tag")

tag
      6455658
GR      10824
S        8670
G        1423
F         337
I          74
H          27
D           3
Name: count, dtype: int64

In [4]:
emlap_metadata = pd.read_csv("../data/emlap_metadata.csv", sep=";") # , index=True)

In [10]:
def count_tokens(id):
    subset_N = len(emlap_tokens_df[emlap_tokens_df["id"] == str(int(id))])
    return subset_N

In [11]:
emlap_metadata["tokens_N"] = emlap_metadata["no."].apply(count_tokens)

In [12]:
emlap_metadata["tokens_N"].sum()

np.int64(6477016)

In [13]:
emlap_metadata.to_csv("../data/emlap_metadata.csv", sep=";") # , index=True)

## Emlap textfiles

In [24]:
txt_outpath = "../data/emlap_corpus_public/emlap_txts/"
os.makedirs(txt_outpath, exist_ok=True)

In [25]:
for id in emlap_tokens_df["id"].unique():
    work_tokens_df = emlap_tokens_df[emlap_tokens_df["id"] == id]
    work_raw_str = " ".join(work_tokens_df["token_text"].tolist())
    work_raw_str = re.sub(r'\s+([.,:;?!])', r'\1', work_raw_str)
    with open(txt_outpath + id + ".txt", "w", encoding='utf-8') as f:
        f.write(work_raw_str)

In [ ]:
path_raw_textblocks = "../data/emlap_annotated_textblocks/"
id = 100085
filename = [f for f in os.listdir(path_sanitized_textblocks) if f[:6] == str(id)][0]
with open(os.path.join(path_raw_textblocks, filename), 'r', encoding='utf-8') as f:
    textblocks_raw = json.load(f)
with open(os.path.join(path_sanitized_textblocks, filename), 'r', encoding='utf-8') as f:
    textblocks_sanitized = json.load(f)

In [ ]:
path_sanitized_textblocks = "../data/emlap_sanitized_textblocks/"
path_raw_textblocks = "../data/emlap_annotated_textblocks/"

def show_raw_and_sanitized_textblock(id, page, textblock):
    filename = [f for f in os.listdir(path_sanitized_textblocks) if f[:6] == str(id)][0]
    with open(os.path.join(path_raw_textblocks, filename), 'r', encoding='utf-8') as f:
        textblocks_raw = json.load(f)
    with open(os.path.join(path_sanitized_textblocks, filename), 'r', encoding='utf-8') as f:
        textblocks_sanitized = json.load(f)
    print("filename: ", filename)
    print("page (0-based indexing): ", page)
    print("raw annotated textblock data: ", textblocks_raw[page][textblock])
    print("sanitized annotated textblock data: ", textblocks_sanitized[page][textblock])

In [12]:
show_raw_and_sanitized_textblock(100026, 20, 5)

filename:  100026_Garlandius1560_Compendium_Alchemiae_VD16_SLUB.json
page (0-based indexing):  20
raw annotated textblock data:  {'coordinates': [130.55999755859375, 186.98397827148438, 378.3510437011719, 191.9039764404297], 'text': 'tis Trismegisti [G]περὶ χημείας[/G]\n', 'tag': 'text'}
sanitized annotated textblock data:  {'coordinates': [130.55999755859375, 186.98397827148438, 378.3510437011719, 191.9039764404297], 'text': 'tis Trismegisti [G] περὶ χημείας [/G] ', 'tag': 'text'}

In [13]:
show_raw_and_sanitized_textblock(100085, 96, 23)

filename:  100085_Libavius1606_Commentariorum_alchemiae_pars_1_MDZ_MBS.json
page (0-based indexing):  96
raw annotated textblock data:  {'coordinates': [1060.3199462890625, 1432.823974609375, 1571.1358642578125, 1437.7440185546875], 'text': '[S]Aries[/S]\xa0[S]Taurus[/S]\xa0[S]Gemini[/S]\xa0\xa0[S]Cancer[/S]\xa0[S]]Leo[/S]\xa0\xa0[S]Virgo[/S]\n', 'tag': 'text'}
sanitized annotated textblock data:  {'coordinates': [1060.3199462890625, 1432.823974609375, 1571.1358642578125, 1437.7440185546875], 'text': '[S] aries [/S] [S] taurus [/S] [S] gemini [/S] [S] cancer [/S] [S] leo [/S] [S] uirgo [/S] ', 'tag': 'text'}